### ISSUE TITLE
Pin # required

### ISSUE THREAD

**Issue by TheMlok** [eflukx/nrf24-ruby#1]
Hello,

thanks for your gem. I have an issue with an example. It is not working on Raspberry Pi, because pin setting error.

Traceback (most recent call last):
	5: from test.rb:51:in `<main>'
	4: from test.rb:27:in `classic'
	3: from test.rb:27:in `new'
	2: from /var/lib/gems/2.5.0/gems/nRF24-ruby-0.0.6/lib/nRF24-ruby.rb:424:in `initialize'
	1: from /var/lib/gems/2.5.0/gems/nRF24-ruby-0.0.6/lib/nRF24-ruby.rb:424:in `new'
/var/lib/gems/2.5.0/gems/pi_piper-2.0.0/lib/pi_piper/pin.rb:41:in `initialize': Pin # required (ArgumentError)

It would be great to add the way to configure pins.

Thanks 

Mlok

**Comment by eflukx** [comment]
It has been a looong time since I had my eyes on this code.. 😉 let me look..

When initializing the NRF24 object pin numbers for CE and CSN can be given (defaults to pin 22 and 8)

Snippet from `nrf24-ruby.rb`

```ruby
def initialize opts = {}
    opts = {cepin: 22, csnpin: 8, static_payload_size: 32, channel: 76, driver: Bcm2835Driver}.merge opts
```

e.g. `nrf = NRF24.new(cepin: 5, csnpin: 6)` initialises the driver for pin 5 and 6

Furthermore, a completely custom driver (module) can be given optionally, which defaults to the `Bcm2835Driver` module. The methods to be implemented in this driver module can be copied from the module in  `bcm2835_driver.rb`

**Comment by TheMlok** [comment]
Understand, I know that situation :) 

we tried according snippet, but also these arguments are not passed to Pi Piper.

[1] pry(#<test>)> nrf = NRF24.new(cepin: 22, csnpin: 24)
ArgumentError: Pin # required
from /var/lib/gems/2.5.0/gems/pi_piper-2.0.0/lib/pi_piper/pin.rb:41:in `initialize'

**Comment by eflukx** [comment]
As said.. it is a while since I last touched this code. As far as I can recall, I did not use the PiPiper gem. 
There's another (old) gem called `bcm2835`, which is no more then a direct wrapper of the BCM2835 C library. I think I based this nrf24 lib on that gem. 

I think PiPiper (or any other GPIO gem/lib) can also be used if you implement a correct `driver`

**Comment by TheMlok** [comment]
Oh my ... I'm sorry, I did not noticed that there is a different gem almost the same name nRF24-ruby, which is different. Little bit mad of reading tons of foreign code, sorry. I would like to use yours, I will install it. 

https://rubygems.org/gems/nRF24-ruby/versions/0.0.6

from another author :) sorry for my stupidity.

**Comment by eflukx** [comment]
Ah yes this naming confusion... when I created this lib, I noticed there was already a gem with a very similar name, apparently that didn't stop me from using it..  :wink:.

The other lib includes some additional parts (e.g. mqtt, http support) and had NodeJS as a dependency, I was looking for a clean-cut Ruby implementation of a nRF24 "driver". So I decided to build my own, mostly meant for personal use at that time. However I released the code on github for whomever to use. I never published the gem to rubygems. So a simple `gem install nrf24-ruby` will yield you an unexpected result. 😲 

To make matters worse, the module called BCM2835 is also present in PiPiper.. ;) So even the dependencies names' can be confusing.. 

Anyway, let me know if you have been able to successfully use this lib. I'm open for comments and/or PR's! One of the main omissions IMO is the handling of IRQ's (asynchronously), currently only polling the radio is supported.

**Comment by TheMlok** [comment]
It is great you created this gem. I would like to use it. I will try to experiment during the weekend and I let you know about the result. I see, now I have a little bit more view into these libraries. I am unix system programmer in one big company, so I know a lot about name/lib/etc confusing :-)

This is my personal project, so I don't have a lots of time for it.

Thank you so much for your work and time.
